/* The following code was generated by JFlex 1.6.1 */

 /*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2016 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2016 Sun Microsystems, Inc.
 */

package org.netbeans.modules.php.blade.editor.lexer;

import java.util.Objects;
import org.netbeans.spi.lexer.LexerInput;
import org.netbeans.spi.lexer.LexerRestartInfo;
import org.netbeans.modules.web.common.api.ByteStack;

@org.netbeans.api.annotations.common.SuppressWarnings({"SF_SWITCH_FALLTHROUGH", "URF_UNREAD_FIELD", "DLS_DEAD_LOCAL_STORE", "DM_DEFAULT_ENCODING", "EI_EXPOSE_REP"})

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/LOCAL_P5_APPS/lmc/blade-php/tools/BladeColoringLexer.flex</tt>
 */
public class BladeColoringLexer {
/** This character denotes the end of file */
  public static final int YYEOF = LexerInput.EOF;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int ST_HTML = 2;
  public static final int ST_PHP = 4;
  public static final int ST_PHP_ECHO = 6;
  public static final int ST_INLINE_PHP = 8;
  public static final int ST_BLADE_PHP = 10;
  public static final int ST_BLADE_ECHO = 12;
  public static final int ST_BLADE_ECHO_ESCAPED = 14;
  public static final int ST_DIRECTIVE = 16;
  public static final int ST_DIRECTIVE_ARGUMENTS = 18;
  public static final int ST_COMMENT = 20;
  public static final int ST_HIGHLIGHTING_ERROR = 22;
  public static final int ST_CLOSE_BLADE_PHP = 24;
  public static final int ST_PHP_LOOKING_FOR_DIRECTIVE_ARG = 26;
  public static final int ST_PHP_LOOKING_FOR_DIRECTIVE_PARAM = 28;
  public static final int ST_PHP_LOOP_EXPR = 30;
  public static final int ST_DIRECTIVE_ARG = 32;
  public static final int ST_PHP_COND_EXPR = 34;
  public static final int ST_CLOSE_PARANTHEIS = 36;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  0,  0,  4,  4,  5,  5,  6,  6, 
     0,  0,  0,  0,  7,  7,  8,  8,  0,  0,  9,  9,  0,  0, 10, 10, 
    11, 11, 12, 12, 13, 13
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\56\1\56\1\2\22\0\1\1\1\6\1\47"+
    "\2\0\1\24\1\0\1\50\1\53\1\54\3\0\1\7\2\0\12\11"+
    "\1\0\1\23\1\13\1\46\1\17\1\14\1\12\1\43\1\10\1\31"+
    "\1\22\1\20\1\55\1\44\1\16\1\35\2\10\1\42\1\41\1\21"+
    "\1\52\1\15\1\10\1\33\1\27\1\37\1\45\2\10\1\40\1\51"+
    "\1\10\4\0\1\10\1\0\1\43\1\10\1\32\1\22\1\20\1\55"+
    "\1\44\1\16\1\36\2\10\1\42\1\41\1\21\1\52\1\26\1\10"+
    "\1\34\1\30\1\25\1\45\2\10\1\40\1\51\1\10\1\4\1\0"+
    "\1\5\1\0\6\10\1\57\44\10\1\10\12\10\1\10\4\10\1\10"+
    "\5\10\27\10\1\10\37\10\1\10\10\10\60\10\2\35\115\10\1\27"+
    "\u0142\10\4\0\14\10\16\0\5\10\7\0\1\10\1\0\1\10\201\0"+
    "\5\10\1\0\2\10\2\0\4\10\1\0\1\10\6\0\1\10\1\0"+
    "\3\10\1\0\1\10\1\0\24\10\1\0\123\10\1\0\213\10\10\0"+
    "\246\10\1\0\46\10\2\0\1\10\7\0\47\10\110\0\33\10\5\0"+
    "\3\10\55\0\53\10\25\0\12\11\4\0\2\10\1\0\143\10\1\0"+
    "\1\10\17\0\2\10\7\0\2\10\12\11\3\10\2\0\1\10\20\0"+
    "\1\10\1\0\36\10\35\0\131\10\13\0\1\10\16\0\12\11\41\10"+
    "\11\0\2\10\4\0\1\10\5\0\26\10\4\0\1\10\11\0\1\10"+
    "\3\0\1\10\27\0\31\10\107\0\23\10\121\0\66\10\3\0\1\10"+
    "\22\0\1\10\7\0\12\10\4\0\12\11\1\0\20\10\4\0\10\10"+
    "\2\0\2\10\2\0\26\10\1\0\7\10\1\0\1\10\3\0\4\10"+
    "\3\0\1\10\20\0\1\10\15\0\2\10\1\0\3\10\4\0\12\11"+
    "\2\10\23\0\6\10\4\0\2\10\2\0\26\10\1\0\7\10\1\0"+
    "\2\10\1\0\2\10\1\0\2\10\37\0\4\10\1\0\1\10\7\0"+
    "\12\11\2\0\3\10\20\0\11\10\1\0\3\10\1\0\26\10\1\0"+
    "\7\10\1\0\2\10\1\0\5\10\3\0\1\10\22\0\1\10\17\0"+
    "\2\10\4\0\12\11\25\0\10\10\2\0\2\10\2\0\26\10\1\0"+
    "\7\10\1\0\2\10\1\0\5\10\3\0\1\10\36\0\2\10\1\0"+
    "\3\10\4\0\12\11\1\0\1\10\21\0\1\10\1\0\6\10\3\0"+
    "\3\10\1\0\4\10\3\0\2\10\1\0\1\10\1\0\2\10\3\0"+
    "\2\10\3\0\3\10\3\0\14\10\26\0\1\10\25\0\12\11\25\0"+
    "\10\10\1\0\3\10\1\0\27\10\1\0\20\10\3\0\1\10\32\0"+
    "\2\10\6\0\2\10\4\0\12\11\25\0\10\10\1\0\3\10\1\0"+
    "\27\10\1\0\12\10\1\0\5\10\3\0\1\10\40\0\1\10\1\0"+
    "\2\10\4\0\12\11\1\0\2\10\22\0\10\10\1\0\3\10\1\0"+
    "\51\10\2\0\1\10\20\0\1\10\21\0\2\10\4\0\12\11\12\0"+
    "\6\10\5\0\22\10\3\0\30\10\1\0\11\10\1\0\1\10\2\0"+
    "\7\10\37\0\12\11\21\0\60\10\1\0\2\10\14\0\7\10\11\0"+
    "\12\11\47\0\2\10\1\0\1\10\2\0\2\10\1\0\1\10\2\0"+
    "\1\10\6\0\4\10\1\0\7\10\1\0\3\10\1\0\1\10\1\0"+
    "\1\10\2\0\2\10\1\0\4\10\1\0\2\10\11\0\1\10\2\0"+
    "\5\10\1\0\1\10\11\0\12\11\2\0\4\10\40\0\1\10\37\0"+
    "\12\11\26\0\10\10\1\0\44\10\33\0\5\10\163\0\53\10\24\0"+
    "\1\10\12\11\6\0\6\10\4\0\4\10\3\0\1\10\3\0\2\10"+
    "\7\0\3\10\4\0\15\10\14\0\1\10\1\0\12\11\6\0\46\10"+
    "\1\0\1\10\5\0\1\10\2\0\53\10\1\0\u014d\10\1\0\4\10"+
    "\2\0\7\10\1\0\1\10\1\0\4\10\2\0\51\10\1\0\4\10"+
    "\2\0\41\10\1\0\4\10\2\0\7\10\1\0\1\10\1\0\4\10"+
    "\2\0\17\10\1\0\71\10\1\0\4\10\2\0\103\10\45\0\20\10"+
    "\20\0\125\10\14\0\u026c\10\2\0\21\10\1\0\32\10\5\0\113\10"+
    "\6\0\10\10\7\0\15\10\1\0\4\10\16\0\22\10\16\0\22\10"+
    "\16\0\15\10\1\0\3\10\17\0\64\10\43\0\1\10\4\0\1\10"+
    "\3\0\12\11\46\0\12\11\6\0\130\10\10\0\51\10\1\0\1\10"+
    "\5\0\106\10\12\0\37\10\47\0\12\11\36\10\2\0\5\10\13\0"+
    "\54\10\25\0\7\10\10\0\12\11\46\0\27\10\11\0\65\10\53\0"+
    "\12\11\6\0\12\11\15\0\1\10\135\0\57\10\21\0\7\10\4\0"+
    "\12\11\51\0\36\10\15\0\2\10\12\11\54\10\32\0\44\10\34\0"+
    "\12\11\3\0\3\10\12\11\44\10\153\0\4\10\1\0\4\10\3\0"+
    "\2\10\11\0\300\10\100\0\u0116\10\2\0\6\10\2\0\46\10\2\0"+
    "\6\10\2\0\10\10\1\0\1\10\1\0\1\10\1\0\1\10\1\0"+
    "\37\10\2\0\65\10\1\0\7\10\1\0\1\10\3\0\3\10\1\0"+
    "\7\10\3\0\4\10\2\0\6\10\4\0\15\10\5\0\3\10\1\0"+
    "\7\10\53\0\1\56\1\56\107\0\1\10\15\0\1\10\20\0\15\10"+
    "\145\0\1\10\4\0\1\10\2\0\12\10\1\0\1\10\3\0\5\10"+
    "\6\0\1\10\1\0\1\10\1\0\1\10\1\0\4\10\1\0\13\10"+
    "\2\0\4\10\5\0\5\10\4\0\1\10\64\0\2\10\u0a7b\0\57\10"+
    "\1\0\57\10\1\0\205\10\6\0\4\10\3\0\2\10\14\0\46\10"+
    "\1\0\1\10\5\0\1\10\2\0\70\10\7\0\1\10\20\0\27\10"+
    "\11\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10"+
    "\1\0\7\10\1\0\7\10\1\0\7\10\120\0\1\10\u01d5\0\2\10"+
    "\52\0\5\10\5\0\2\10\4\0\126\10\6\0\3\10\1\0\132\10"+
    "\1\0\4\10\5\0\51\10\3\0\136\10\21\0\33\10\65\0\20\10"+
    "\u0200\0\u19b6\10\112\0\u51cd\10\63\0\u048d\10\103\0\56\10\2\0\u010d\10"+
    "\3\0\20\10\12\11\2\10\24\0\57\10\20\0\37\10\2\0\106\10"+
    "\61\0\11\10\2\0\147\10\2\0\4\10\1\0\36\10\2\0\2\10"+
    "\105\0\13\10\1\0\3\10\1\0\4\10\1\0\27\10\35\0\64\10"+
    "\16\0\62\10\34\0\12\11\30\0\6\10\3\0\1\10\4\0\12\11"+
    "\34\10\12\0\27\10\31\0\35\10\7\0\57\10\34\0\1\10\12\11"+
    "\6\0\5\10\1\0\12\10\12\11\5\10\1\0\51\10\27\0\3\10"+
    "\1\0\10\10\4\0\12\11\6\0\27\10\3\0\1\10\3\0\62\10"+
    "\1\0\1\10\3\0\2\10\2\0\5\10\2\0\1\10\1\0\1\10"+
    "\30\0\3\10\2\0\13\10\7\0\3\10\14\0\6\10\2\0\6\10"+
    "\2\0\6\10\11\0\7\10\1\0\7\10\1\0\53\10\1\0\4\10"+
    "\4\0\2\10\132\0\43\10\15\0\12\11\6\0\u2ba4\10\14\0\27\10"+
    "\4\0\61\10\u2104\0\u016e\10\2\0\152\10\46\0\7\10\14\0\5\10"+
    "\5\0\1\10\1\0\12\10\1\0\15\10\1\0\5\10\1\0\1\10"+
    "\1\0\2\10\1\0\2\10\1\0\154\10\41\0\u016b\10\22\0\100\10"+
    "\2\0\66\10\50\0\14\10\164\0\5\10\1\0\207\10\23\0\12\11"+
    "\7\0\32\10\6\0\32\10\13\0\131\10\3\0\6\10\2\0\6\10"+
    "\2\0\6\10\2\0\3\10\43\0\14\10\1\0\32\10\1\0\23\10"+
    "\1\0\2\10\1\0\17\10\2\0\16\10\42\0\173\10\u0185\0\35\10"+
    "\3\0\61\10\57\0\40\10\20\0\21\10\1\0\10\10\6\0\46\10"+
    "\12\0\36\10\2\0\44\10\4\0\10\10\60\0\236\10\2\0\12\11"+
    "\126\0\50\10\10\0\64\10\234\0\u0137\10\11\0\26\10\12\0\10\10"+
    "\230\0\6\10\2\0\1\10\1\0\54\10\1\0\2\10\3\0\1\10"+
    "\2\0\27\10\12\0\27\10\11\0\37\10\141\0\26\10\12\0\32\10"+
    "\106\0\70\10\6\0\2\10\100\0\1\10\17\0\4\10\1\0\3\10"+
    "\1\0\33\10\54\0\35\10\3\0\35\10\43\0\10\10\1\0\34\10"+
    "\33\0\66\10\12\0\26\10\12\0\23\10\15\0\22\10\156\0\111\10"+
    "\u03ba\0\65\10\56\0\12\11\23\0\55\10\40\0\31\10\7\0\12\11"+
    "\11\0\44\10\17\0\12\11\20\0\43\10\3\0\1\10\14\0\60\10"+
    "\16\0\4\10\13\0\12\11\1\10\45\0\22\10\1\0\31\10\204\0"+
    "\57\10\21\0\12\11\13\0\10\10\2\0\2\10\2\0\26\10\1\0"+
    "\7\10\1\0\2\10\1\0\5\10\3\0\1\10\37\0\5\10\u011e\0"+
    "\60\10\24\0\2\10\1\0\1\10\10\0\12\11\246\0\57\10\121\0"+
    "\60\10\24\0\1\10\13\0\12\11\46\0\53\10\25\0\12\11\u01d6\0"+
    "\100\10\12\11\25\0\1\10\u01c0\0\71\10\u0507\0\u0399\10\u0c67\0\u042f\10"+
    "\u33d1\0\u0239\10\7\0\37\10\1\0\12\11\146\0\36\10\22\0\60\10"+
    "\20\0\4\10\14\0\12\11\11\0\25\10\5\0\23\10\u0370\0\105\10"+
    "\13\0\1\10\102\0\15\10\u4060\0\2\10\u0bfe\0\153\10\5\0\15\10"+
    "\3\0\11\10\7\0\12\10\u1766\0\125\10\1\0\107\10\1\0\2\10"+
    "\2\0\1\10\2\0\2\10\2\0\4\10\1\0\14\10\1\0\1\10"+
    "\1\0\7\10\1\0\101\10\1\0\4\10\2\0\10\10\1\0\7\10"+
    "\1\0\34\10\1\0\4\10\1\0\5\10\1\0\1\10\3\0\7\10"+
    "\1\0\u0154\10\2\0\31\10\1\0\31\10\1\0\37\10\1\0\31\10"+
    "\1\0\37\10\1\0\31\10\1\0\37\10\1\0\31\10\1\0\37\10"+
    "\1\0\31\10\1\0\10\10\2\0\62\11\u1000\0\305\10\u053b\0\4\10"+
    "\1\0\33\10\1\0\2\10\1\0\1\10\2\0\1\10\1\0\12\10"+
    "\1\0\4\10\1\0\1\10\1\0\1\10\6\0\1\10\4\0\1\10"+
    "\1\0\1\10\1\0\1\10\1\0\3\10\1\0\2\10\1\0\1\10"+
    "\2\0\1\10\1\0\1\10\1\0\1\10\1\0\1\10\1\0\1\10"+
    "\1\0\2\10\1\0\1\10\2\0\4\10\1\0\7\10\1\0\4\10"+
    "\1\0\4\10\1\0\1\10\1\0\12\10\1\0\21\10\5\0\3\10"+
    "\1\0\5\10\1\0\21\10\u1144\0\ua6d7\10\51\0\u1035\10\13\0\336\10"+
    "\u3fe2\0\u021e\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05f0\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\16\0\1\1\1\2\2\3\1\1\1\3\1\1\1\3"+
    "\1\0\1\3\2\0\1\3\1\0\2\3\1\4\2\5"+
    "\1\3\1\0\1\3\1\4\2\5\1\3\3\0\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\0\1\20\1\0\1\21\1\1\1\22"+
    "\7\23\3\0\1\24\1\0\1\25\3\0\1\26\5\0"+
    "\1\27\1\23\1\30\5\23\1\31\2\23\2\0\1\32"+
    "\1\0\1\33\1\34\2\0\2\35\1\0\1\26\2\0"+
    "\1\36\1\37\4\23\1\31\1\23\1\40\5\0\1\41"+
    "\1\0\1\42\1\37\7\23\1\40\1\23\1\43\3\0"+
    "\1\44\6\23\1\45\1\23\3\0\2\23\1\46\3\23"+
    "\1\45\1\23\1\1\1\0\1\47\1\50\1\23\1\46"+
    "\1\23\1\51\1\52\1\53\1\54\1\0\1\47\1\55"+
    "\2\23\1\51\1\52\1\53\1\54\1\0\2\23\1\0"+
    "\1\56\1\57\1\0\1\56\1\57\21\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\360\0\u0120\0\u0150"+
    "\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270\0\u02a0\0\u02d0"+
    "\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0\0\u03f0\0\u0420"+
    "\0\u0450\0\u0480\0\u04b0\0\u04b0\0\u04e0\0\u0510\0\u0540\0\u0570"+
    "\0\u0540\0\u05a0\0\u0510\0\u05d0\0\u0600\0\u0630\0\u0600\0\u0660"+
    "\0\u05d0\0\u0690\0\u06c0\0\0\0\u06f0\0\0\0\0\0\0"+
    "\0\0\0\0\0\0\0\0\0\0\0\0\0\u0720\0\u0750"+
    "\0\u0780\0\0\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0"+
    "\0\u08d0\0\u0900\0\u0930\0\u0960\0\u0990\0\u09c0\0\0\0\u09f0"+
    "\0\0\0\u0a20\0\u0a50\0\u0a80\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40"+
    "\0\u0b70\0\u0ba0\0\0\0\u0bd0\0\0\0\u0c00\0\u0c30\0\u0c60"+
    "\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20\0\u0d50\0\u0d80\0\u0db0\0\0"+
    "\0\u0de0\0\0\0\0\0\u0e10\0\u0e40\0\u0ab0\0\0\0\u0e70"+
    "\0\0\0\u0ea0\0\u0ed0\0\0\0\u0f00\0\u0f30\0\u0f60\0\u0f90"+
    "\0\u0fc0\0\u0ff0\0\u1020\0\u1050\0\u1080\0\u10b0\0\u10e0\0\u1110"+
    "\0\u1140\0\0\0\u1170\0\0\0\u11a0\0\u11d0\0\u1200\0\u1230"+
    "\0\u1260\0\u1290\0\u12c0\0\u12f0\0\u1320\0\u1350\0\0\0\u1380"+
    "\0\u13b0\0\u13e0\0\0\0\u1410\0\u1440\0\u1470\0\u14a0\0\u14d0"+
    "\0\u1500\0\u1530\0\u1560\0\u1590\0\u15c0\0\u15f0\0\u1620\0\u1650"+
    "\0\u1680\0\u16b0\0\u16e0\0\u1710\0\u1740\0\u1770\0\u17a0\0\u17d0"+
    "\0\u1800\0\0\0\u1830\0\u1860\0\u1890\0\u18c0\0\u18f0\0\u1920"+
    "\0\u1950\0\u1980\0\0\0\0\0\u19b0\0\u19e0\0\u1a10\0\u1a40"+
    "\0\u1a70\0\u1aa0\0\u1ad0\0\u1b00\0\u1b30\0\u1b60\0\u1b90\0\u1bc0"+
    "\0\u1bf0\0\u1c20\0\u1c50\0\u1c80\0\u1cb0\0\u1ce0\0\u1d10\0\u1d40"+
    "\0\u1d70\0\u1da0\0\u1dd0\0\u1e00\0\u1e30\0\u1e60\0\u1e90\0\u1ec0"+
    "\0\u1ef0\0\u1f20\0\u1f50\0\u1f80";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\60\0\1\17\3\20\1\21\1\22\1\23\3\17\1\24"+
    "\1\25\44\17\2\26\2\27\10\26\1\30\41\26\2\27"+
    "\14\31\1\32\43\31\2\33\2\34\6\33\1\35\43\33"+
    "\2\34\1\36\1\37\1\40\1\41\1\36\1\42\50\36"+
    "\2\43\1\44\1\45\1\46\1\47\2\44\1\50\47\44"+
    "\2\51\7\52\1\53\50\52\1\54\3\55\52\54\2\0"+
    "\53\56\1\57\1\60\3\56\54\13\1\61\3\13\53\62"+
    "\1\63\1\64\3\62\54\15\1\65\3\15\54\0\1\66"+
    "\3\0\4\17\2\0\4\17\1\0\1\67\45\17\3\20"+
    "\2\0\4\17\1\0\1\67\44\17\4\0\1\70\1\0"+
    "\1\71\56\0\1\72\52\0\4\17\2\0\1\73\3\17"+
    "\1\0\1\67\44\17\1\0\3\74\4\0\1\75\4\0"+
    "\1\76\1\75\1\0\1\77\2\75\2\0\1\75\1\76"+
    "\2\100\4\75\2\101\7\75\3\0\1\102\1\75\2\0"+
    "\1\103\1\0\1\75\13\17\1\0\1\104\7\17\3\0"+
    "\1\17\1\105\1\17\1\0\1\17\1\0\1\17\1\0"+
    "\14\17\2\0\3\17\14\27\1\106\57\27\1\106\2\27"+
    "\1\107\40\27\14\31\1\110\57\31\1\110\2\31\1\111"+
    "\40\31\12\34\1\112\57\34\1\112\5\34\1\113\37\34"+
    "\5\43\1\114\53\43\3\37\1\43\1\114\53\43\2\37"+
    "\1\41\1\43\1\114\57\43\1\115\52\43\6\51\1\116"+
    "\52\51\3\45\2\51\1\116\52\51\2\45\1\47\2\51"+
    "\1\116\57\51\1\117\51\51\7\52\1\120\57\52\1\121"+
    "\50\52\1\0\3\55\54\0\13\17\2\0\7\17\3\0"+
    "\1\17\1\0\1\17\1\0\1\17\1\0\1\17\1\0"+
    "\14\17\2\0\3\17\7\0\1\122\56\0\1\123\51\0"+
    "\4\17\1\0\1\72\4\17\1\0\1\67\44\17\1\0"+
    "\3\74\55\0\3\124\4\0\2\75\3\0\2\75\1\0"+
    "\3\75\2\0\21\75\3\0\2\75\1\125\1\0\1\75"+
    "\1\0\1\75\1\0\3\124\4\0\2\75\3\0\1\75"+
    "\1\126\1\0\3\75\2\0\21\75\3\0\2\75\1\125"+
    "\1\0\1\75\1\0\1\75\1\0\3\124\4\0\2\75"+
    "\3\0\2\75\1\0\1\75\1\127\1\75\2\0\13\75"+
    "\1\130\5\75\3\0\2\75\1\125\1\0\1\75\1\0"+
    "\1\75\1\0\3\124\4\0\2\75\3\0\2\75\1\0"+
    "\1\131\2\75\2\0\21\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\124\4\0\2\75\3\0"+
    "\2\75\1\0\1\75\1\132\1\75\2\0\21\75\3\0"+
    "\2\75\1\125\1\0\1\133\1\0\1\75\1\0\3\124"+
    "\4\0\2\75\3\0\2\75\1\0\3\75\2\0\10\75"+
    "\2\134\7\75\3\0\2\75\1\125\1\0\1\75\1\0"+
    "\1\75\1\0\3\124\4\0\2\75\3\0\2\75\1\0"+
    "\3\75\2\0\21\75\3\0\1\75\1\135\1\125\1\0"+
    "\1\75\1\0\1\75\15\0\1\136\10\0\1\136\11\0"+
    "\1\137\5\0\1\140\42\0\2\141\25\0\14\27\1\106"+
    "\2\27\1\142\40\27\14\31\1\110\2\31\1\143\40\31"+
    "\12\34\1\112\5\34\1\144\51\34\1\112\6\34\1\145"+
    "\36\34\5\43\1\146\52\43\5\0\1\147\52\0\6\51"+
    "\1\150\56\51\1\151\1\150\51\51\7\52\1\152\55\52"+
    "\1\153\1\52\1\152\50\52\7\0\1\154\51\0\3\124"+
    "\47\0\1\125\5\0\3\124\4\0\2\75\3\0\1\155"+
    "\1\75\1\0\3\75\2\0\1\75\1\155\17\75\3\0"+
    "\2\75\1\125\1\0\1\75\1\0\1\75\1\0\3\124"+
    "\4\0\2\75\3\0\2\75\1\0\2\75\1\156\2\0"+
    "\21\75\3\0\2\75\1\125\1\0\1\75\1\0\1\75"+
    "\1\0\3\124\4\0\2\75\3\0\2\75\1\0\3\75"+
    "\2\0\1\157\11\75\1\157\6\75\3\0\2\75\1\125"+
    "\1\0\1\75\1\0\1\75\1\0\3\124\4\0\2\75"+
    "\3\0\2\75\1\0\3\75\2\0\4\75\2\160\13\75"+
    "\3\0\2\75\1\125\1\0\1\75\1\0\1\75\1\0"+
    "\3\124\4\0\2\75\3\0\2\75\1\0\3\75\2\0"+
    "\4\75\2\161\13\75\3\0\2\75\1\125\1\0\1\75"+
    "\1\0\1\75\1\0\3\162\4\0\2\75\3\0\2\75"+
    "\1\0\3\75\2\0\21\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\124\4\0\2\75\3\0"+
    "\2\75\1\0\1\163\2\75\2\0\21\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\1\0\3\124\4\0"+
    "\2\75\3\0\2\75\1\0\3\75\2\0\6\75\2\164"+
    "\11\75\3\0\2\75\1\125\1\0\1\75\1\0\1\75"+
    "\16\0\1\165\102\0\1\166\51\0\2\167\23\0\12\34"+
    "\1\112\6\34\1\170\50\34\1\112\7\34\1\171\35\34"+
    "\5\51\1\172\1\150\51\51\5\52\1\173\1\52\1\152"+
    "\55\52\1\174\1\52\1\120\50\52\1\0\3\175\4\0"+
    "\2\75\3\0\2\75\1\0\3\75\2\0\21\75\3\0"+
    "\2\75\1\125\1\0\1\75\1\0\1\75\1\0\3\124"+
    "\4\0\2\75\3\0\1\176\1\75\1\0\3\75\2\0"+
    "\1\75\1\176\2\177\15\75\3\0\2\75\1\125\1\0"+
    "\1\200\1\0\1\75\1\0\3\124\4\0\2\75\3\0"+
    "\2\75\1\0\1\201\2\75\2\0\21\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\1\0\3\124\4\0"+
    "\2\75\3\0\2\75\1\0\3\75\2\0\1\202\11\75"+
    "\1\202\6\75\3\0\2\75\1\125\1\0\1\75\1\0"+
    "\1\75\1\0\3\124\4\0\2\75\3\0\2\75\1\0"+
    "\3\75\2\0\15\75\1\203\3\75\3\0\2\75\1\125"+
    "\1\0\1\75\1\0\1\75\1\0\3\162\47\0\1\125"+
    "\5\0\3\124\4\0\2\75\3\0\2\75\1\0\3\75"+
    "\2\0\15\75\1\204\3\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\205\4\0\2\75\3\0"+
    "\2\75\1\0\1\206\2\75\2\0\21\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\15\0\1\207\10\0"+
    "\1\207\73\0\1\54\52\0\2\210\21\0\12\34\1\112"+
    "\7\34\1\211\47\34\1\112\2\34\1\212\10\34\1\212"+
    "\31\34\5\52\1\213\1\52\1\120\50\52\1\0\3\175"+
    "\47\0\1\125\5\0\3\124\4\0\2\75\3\0\1\75"+
    "\1\214\1\0\3\75\2\0\21\75\3\0\2\75\1\125"+
    "\1\0\1\75\1\0\1\75\1\0\3\124\4\0\2\75"+
    "\3\0\2\75\1\0\1\215\2\75\2\0\21\75\3\0"+
    "\2\75\1\125\1\0\1\75\1\0\1\75\1\0\3\124"+
    "\4\0\2\75\3\0\2\75\1\0\3\75\2\0\21\75"+
    "\3\0\1\75\1\216\1\125\1\0\1\75\1\0\1\75"+
    "\1\0\3\124\4\0\2\75\3\0\2\75\1\0\1\75"+
    "\1\217\1\75\2\0\21\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\124\4\0\2\75\3\0"+
    "\2\75\1\0\3\75\2\0\10\75\2\220\7\75\3\0"+
    "\2\75\1\125\1\0\1\75\1\0\1\75\1\0\3\124"+
    "\4\0\2\75\3\0\2\75\1\0\3\75\2\0\20\75"+
    "\1\221\3\0\2\75\1\125\1\0\1\75\1\0\1\75"+
    "\1\0\3\124\4\0\2\75\3\0\2\75\1\0\2\75"+
    "\1\222\2\0\21\75\3\0\2\75\1\125\1\0\1\75"+
    "\1\0\1\75\1\0\3\205\47\0\1\125\5\0\3\124"+
    "\4\0\2\75\3\0\2\75\1\0\3\75\2\0\16\75"+
    "\1\223\2\75\3\0\2\75\1\125\1\0\1\75\1\0"+
    "\1\75\15\0\1\224\10\0\1\224\31\0\12\34\1\112"+
    "\2\34\1\225\10\34\1\225\43\34\1\112\3\34\1\226"+
    "\41\34\1\0\3\124\4\0\2\75\3\0\1\227\1\75"+
    "\1\0\3\75\2\0\1\75\1\227\17\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\1\0\3\124\4\0"+
    "\2\75\3\0\2\75\1\0\3\75\2\0\4\75\2\230"+
    "\13\75\3\0\2\75\1\125\1\0\1\75\1\0\1\75"+
    "\1\0\3\124\4\0\2\75\3\0\2\75\1\0\3\75"+
    "\2\0\6\75\2\231\11\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\124\4\0\2\75\3\0"+
    "\2\75\1\0\2\75\1\232\2\0\21\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\1\0\3\124\4\0"+
    "\2\75\3\0\2\75\1\0\3\75\2\0\21\75\3\0"+
    "\1\75\1\233\1\125\1\0\1\75\1\0\1\75\1\0"+
    "\3\124\4\0\2\75\3\0\2\75\1\0\2\75\1\234"+
    "\2\0\21\75\3\0\2\75\1\125\1\0\1\75\1\0"+
    "\1\75\1\0\3\235\4\0\2\75\3\0\2\75\1\0"+
    "\3\75\2\0\21\75\3\0\2\75\1\125\1\0\1\75"+
    "\1\0\1\75\1\0\3\124\4\0\2\75\3\0\2\75"+
    "\1\0\3\75\2\0\4\75\2\236\13\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\25\0\1\237\11\0"+
    "\1\237\20\0\12\34\1\112\3\34\1\240\53\34\1\112"+
    "\2\34\1\241\10\34\1\241\31\34\1\0\3\124\4\0"+
    "\2\75\3\0\2\75\1\0\3\75\1\242\1\0\21\75"+
    "\3\0\2\75\1\125\1\0\1\75\1\0\1\75\1\0"+
    "\3\124\4\0\2\75\3\0\2\75\1\0\3\75\2\0"+
    "\1\243\11\75\1\243\6\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\244\4\0\2\75\3\0"+
    "\2\75\1\0\1\245\2\75\2\0\21\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\1\0\3\124\4\0"+
    "\2\75\3\0\2\75\1\0\3\75\2\0\2\75\2\246"+
    "\15\75\3\0\2\75\1\125\1\0\1\75\1\0\1\75"+
    "\1\0\3\124\4\0\2\75\3\0\2\75\1\0\1\75"+
    "\1\247\1\75\2\0\21\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\124\4\0\2\75\3\0"+
    "\2\75\1\0\1\250\2\75\2\0\21\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\1\0\3\235\47\0"+
    "\1\125\5\0\3\124\4\0\2\75\3\0\1\75\1\251"+
    "\1\0\3\75\2\0\21\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\252\54\0\12\34\1\112"+
    "\2\34\1\253\10\34\1\253\31\34\23\0\1\254\35\0"+
    "\3\124\4\0\2\75\3\0\2\75\1\0\3\75\2\0"+
    "\10\75\2\255\7\75\3\0\2\75\1\125\1\0\1\75"+
    "\1\0\1\75\1\0\3\244\47\0\1\125\5\0\3\124"+
    "\4\0\2\75\3\0\2\75\1\0\3\75\2\0\16\75"+
    "\1\256\2\75\3\0\2\75\1\125\1\0\1\75\1\0"+
    "\1\75\1\0\3\257\4\0\2\75\3\0\2\75\1\0"+
    "\3\75\2\0\21\75\3\0\2\75\1\125\1\0\1\75"+
    "\1\0\1\75\1\0\3\260\4\0\2\75\3\0\2\75"+
    "\1\0\3\75\2\0\21\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\261\4\0\2\75\3\0"+
    "\2\75\1\0\3\75\2\0\21\75\3\0\2\75\1\125"+
    "\1\0\1\75\1\0\1\75\1\0\3\262\4\0\2\75"+
    "\3\0\2\75\1\0\3\75\2\0\21\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\1\0\3\252\36\0"+
    "\1\263\16\0\3\124\4\0\2\75\3\0\2\75\1\0"+
    "\3\75\2\0\21\75\3\0\1\75\1\264\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\124\4\0\2\75\3\0"+
    "\2\75\1\0\3\75\2\0\4\75\2\265\13\75\3\0"+
    "\2\75\1\125\1\0\1\75\1\0\1\75\1\0\3\257"+
    "\47\0\1\125\5\0\3\260\47\0\1\125\5\0\3\261"+
    "\47\0\1\125\5\0\3\262\47\0\1\125\47\0\1\266"+
    "\15\0\3\124\4\0\2\75\3\0\2\75\1\0\1\75"+
    "\1\267\1\75\2\0\21\75\3\0\2\75\1\125\1\0"+
    "\1\75\1\0\1\75\1\0\3\124\4\0\2\75\3\0"+
    "\1\75\1\270\1\0\3\75\2\0\21\75\3\0\2\75"+
    "\1\125\1\0\1\75\1\0\1\75\21\0\1\271\37\0"+
    "\3\272\4\0\2\75\3\0\2\75\1\0\3\75\2\0"+
    "\21\75\3\0\2\75\1\125\1\0\1\75\1\0\1\75"+
    "\1\0\3\273\4\0\2\75\3\0\2\75\1\0\3\75"+
    "\2\0\21\75\3\0\2\75\1\125\1\0\1\75\1\0"+
    "\1\75\44\0\1\274\14\0\3\272\47\0\1\125\5\0"+
    "\3\273\47\0\1\125\51\0\1\275\55\0\1\276\60\0"+
    "\1\277\33\0\1\300\40\0\3\300\42\0\1\301\12\0"+
    "\3\301\11\0\1\302\10\0\1\302\20\0\1\303\1\304"+
    "\25\0\1\305\56\0\1\306\10\0\1\306\46\0\1\307"+
    "\10\0\1\307\46\0\1\310\10\0\1\310\47\0\1\311"+
    "\57\0\1\312\42\0\3\310\13\0\1\54\55\0\1\313"+
    "\10\0\1\313\46\0\1\314\10\0\1\314\100\0\1\310"+
    "\60\0\1\310\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8112];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\10\15\0\10\1\1\0\1\1\2\0\1\1\1\0"+
    "\6\1\1\0\5\1\3\0\1\11\1\1\11\11\1\0"+
    "\1\1\1\0\1\11\11\1\3\0\1\11\1\0\1\11"+
    "\3\0\1\1\5\0\1\11\1\1\1\11\10\1\2\0"+
    "\1\11\1\0\2\11\2\0\1\1\1\11\1\0\1\11"+
    "\2\0\1\11\10\1\5\0\1\11\1\0\1\11\12\1"+
    "\1\11\3\0\1\11\10\1\3\0\11\1\1\0\1\1"+
    "\1\11\7\1\1\0\2\11\6\1\1\0\2\1\1\0"+
    "\2\1\1\0\2\1\21\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[204];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the
   * matched text
   */
  private int yycolumn;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF = false;

  /* user code: */
    private ByteStack stack = new ByteStack();
    private LexerInput input;
    private int parenBalanceInDirective = 0; //for directive arguments

    public BladeColoringLexer(LexerRestartInfo info) {
        this.input = info.input();
        if(info.state() != null) {
            //reset state
            setState((LexerState) info.state(), parenBalanceInDirective);
        } else {
            //initial state
            stack.push(ST_HTML);
            zzState = ST_HTML;
            zzLexicalState = ST_HTML;
        }

    }

    public static final class LexerState  {
        final ByteStack stack;
        /** the current state of the DFA */
        final int zzState;
        /** the current lexical state */
        final int zzLexicalState;
        final int parenBalanceInDirective; 

        LexerState(ByteStack stack, int zzState, int zzLexicalState, int parenBalanceInDirective) {
            this.stack = stack;
            this.zzState = zzState;
            this.zzLexicalState = zzLexicalState;
            this.parenBalanceInDirective = parenBalanceInDirective;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj == null || obj.getClass() != this.getClass()) {
                return false;
            }
            LexerState state = (LexerState) obj;
            return (this.stack.equals(state.stack)
                && (this.zzState == state.zzState)
                //&& (this.zzLexicalState == state.zzLexicalState)
                //&& (this.parenBalanceInDirective == state.parenBalanceInDirective)
                );
        }

        @Override
        public int hashCode() {
            int hash = 11;
            hash = 31 * hash + this.zzState;
            hash = 31 * hash + this.zzLexicalState;
            hash = 31 * hash + this.parenBalanceInDirective;
            if (stack != null) {
                hash = 31 * hash + this.stack.hashCode();
            }
            return hash;
        }
    }

    public LexerState getState() {
        return new LexerState(stack.copyOf(), zzState, zzLexicalState, parenBalanceInDirective);
    }

    public void setState(LexerState state, int parenBalanceInDirective) {
        this.stack.copyFrom(state.stack);
        this.zzState = state.zzState;
        this.zzLexicalState = state.zzLexicalState;
        this.parenBalanceInDirective = state.parenBalanceInDirective;
    }

    protected int getZZLexicalState() {
        return zzLexicalState;
    }

    //other functions

    protected void pushBack(int i) {
        yypushback(i);
    }

    protected void popState() {
        yybegin(stack.pop());
    }

    protected void pushState(final int state) {
        stack.push(getZZLexicalState());
        yybegin(state);
    }

    /**
     * Returns the smallest of multiple index values.
     *
     * @param values values
     * @return the smallest of multiple index values, -1 if all values are -1
     */
    private static int minIndex(int... values) {
        assert values.length != 0 : "No values"; // NOI18N
        boolean first = true;
        int min = -1;
        for (int value : values) {
            if (value == -1) {
                continue;
            }
            if (first) {
                first = false;
                min = value;
                continue;
            }
            min = Math.min(min, value);
        }
        return min;
    }

    /**
     * Get the first whitespace index of text.
     *
     * @param text the text
     * @return the first index of whitespace if whitespace exists, otherwise -1
     */
    private static int firstWhitespaceIndexOf(String text) {
        return minIndex(
            text.indexOf(' '),
            text.indexOf('\n'),
            text.indexOf('\r'),
            text.indexOf('\t')
        );
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public BladeColoringLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2514) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }



  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return input.readText().toString();
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
     return input.readText().charAt(pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return input.readLength();
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    input.backup(number);
    //zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public BladeTokenId findNextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    //int zzCurrentPosL;
    //int zzMarkedPosL;
    //int zzEndReadL = zzEndRead;
    //char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      //zzMarkedPosL = zzMarkedPos;


      zzAction = -1;

      //zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
      int tokenLength = 0;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
            zzInput = input.read();

            if(zzInput == LexerInput.EOF) {
                //end of input reached
                zzInput = YYEOF;
                break zzForAction;
                //notice: currently LexerInput.EOF == YYEOF
            }

          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            tokenLength = input.readLength();
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      if(zzInput != YYEOF) {
         input.backup(input.readLength() - tokenLength);
      }


        //action
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return BladeTokenId.T_HTML;
            }
          case 48: break;
          case 2: 
            { String yytext = yytext();
	//whitespace
    return BladeTokenId.WHITESPACE;
            }
          case 49: break;
          case 3: 
            { //if (yylength() > 1) {
        //    yypushback(1);
        //}
        //pushState(ST_HIGHLIGHTING_ERROR);
            }
          case 50: break;
          case 4: 
            { //no break;
            }
          case 51: break;
          case 5: 
            { String yytext = yytext();
    popState();
    return BladeTokenId.T_HTML;
            }
          case 52: break;
          case 6: 
            { popState();
        return BladeTokenId.T_HTML;
            }
          case 53: break;
          case 7: 
            { String yytext = yytext();
    int debug = 1;
            }
          case 54: break;
          case 8: 
            { //directive paranthesis
    return BladeTokenId.BLADE_PHP_TOKEN;
            }
          case 55: break;
          case 9: 
            { //directive end
                if (yylength() == 1){
        popState();
        return BladeTokenId.BLADE_PHP_TOKEN;
    }
    yypushback(1);
	popState();
    return BladeTokenId.T_BLADE_PHP_VAR;
            }
          case 56: break;
          case 10: 
            { yypushback(1);
    popState();
    return BladeTokenId.T_BLADE_PHP_LOOP_PARAM;
            }
          case 57: break;
          case 11: 
            { String yytext = yytext();
	int test = 1;
            }
          case 58: break;
          case 12: 
            { String yytext = yytext();
    parenBalanceInDirective++;
    if (parenBalanceInDirective == 1){
        //first paranthesis
    	return BladeTokenId.BLADE_PHP_TOKEN;
    }
            }
          case 59: break;
          case 13: 
            { String yytext = yytext();
    parenBalanceInDirective--;
    if (parenBalanceInDirective <= 0){
        if (yylength() == 1){
           popState();
           return BladeTokenId.BLADE_PHP_TOKEN;
        }
        yypushback(1);
        popState();
        pushState(ST_CLOSE_PARANTHEIS);
		return BladeTokenId.T_DIRECTIVE_ARG;
    }
            }
          case 60: break;
          case 14: 
            { yypushback(1);
    popState();
    return BladeTokenId.T_BLADE_PHP_COND;
            }
          case 61: break;
          case 15: 
            { String yytext = yytext();
       popState();
       return BladeTokenId.BLADE_PHP_TOKEN;
            }
          case 62: break;
          case 16: 
            { String yytext = yytext();
    pushState(ST_BLADE_ECHO);
    return BladeTokenId.T_BLADE_OPEN_ECHO;
            }
          case 63: break;
          case 17: 
            { String yytext = yytext();
    return BladeTokenId.T_BLADE_CLOSE_ECHO;
            }
          case 64: break;
          case 18: 
            { return BladeTokenId.T_BLADE_DIRECTIVE_PREFIX;
            }
          case 65: break;
          case 19: 
            { String yytext = yytext();
   return BladeTokenId.T_BLADE_DIRECTIVE;
            }
          case 66: break;
          case 20: 
            { if (yylength() == 2){
	    popState(); 
		return BladeTokenId.T_CLOSE_PHP;
	}
	yypushback(2);
    return BladeTokenId.T_PHP;
            }
          case 67: break;
          case 21: 
            { if (yylength() == 2){
	    popState(); 
		return BladeTokenId.T_CLOSE_PHP;
	}
	yypushback(2);
    return BladeTokenId.T_PHP_ECHO;
            }
          case 68: break;
          case 22: 
            { String yytext = yytext();
    popState();
    return BladeTokenId.T_BLADE_CLOSE_ECHO;
            }
          case 69: break;
          case 23: 
            { String yytext = yytext();
    pushState(ST_BLADE_ECHO_ESCAPED);
    return BladeTokenId.T_BLADE_OPEN_ECHO;
            }
          case 70: break;
          case 24: 
            { //we have a fatal in php embedding in (:)
   pushState(ST_DIRECTIVE_ARG);
   yypushback(1);
   return BladeTokenId.T_BLADE_DIRECTIVE;
            }
          case 71: break;
          case 25: 
            { pushState(ST_PHP_COND_EXPR);
    return BladeTokenId.T_BLADE_IF;
            }
          case 72: break;
          case 26: 
            { pushState(ST_PHP_ECHO);
    return BladeTokenId.T_PHP_OPEN_ECHO;
            }
          case 73: break;
          case 27: 
            { if (yylength() == 2){
       popState();
       return BladeTokenId.T_CLOSE_PHP;
    }
    yypushback(2);
    return BladeTokenId.T_PHP;
            }
          case 74: break;
          case 28: 
            { if (yylength() == 2){
       popState();
       return BladeTokenId.T_CLOSE_PHP;
    }
    yypushback(2);
    return BladeTokenId.T_PHP_ECHO;
            }
          case 75: break;
          case 29: 
            { String yytext = yytext();
    yypushback(2);
    return BladeTokenId.T_BLADE_PHP_ECHO;
            }
          case 76: break;
          case 30: 
            { pushState(ST_COMMENT);
    return BladeTokenId.T_BLADE_COMMENT;
            }
          case 77: break;
          case 31: 
            { pushState(ST_BLADE_PHP);
    return BladeTokenId.T_BLADE_PHP_OPEN;
            }
          case 78: break;
          case 32: 
            { pushState(ST_PHP_LOOP_EXPR);
    return BladeTokenId.T_BLADE_FOR;
            }
          case 79: break;
          case 33: 
            { String yytext = yytext();
    yypushback(3);
    return BladeTokenId.T_BLADE_PHP_ECHO;
            }
          case 80: break;
          case 34: 
            { popState();
    return BladeTokenId.T_BLADE_COMMENT;
            }
          case 81: break;
          case 35: 
            { pushState(ST_PHP);
    return BladeTokenId.T_OPEN_PHP;
            }
          case 82: break;
          case 36: 
            { yypushback(4);
    return BladeTokenId.T_BLADE_COMMENT;
            }
          case 83: break;
          case 37: 
            { return BladeTokenId.T_BLADE_YIELD;
            }
          case 84: break;
          case 38: 
            { return BladeTokenId.T_BLADE_ENDFOR;
            }
          case 85: break;
          case 39: 
            { String ttext = yytext();
    popState();
    if (yylength() == "@endphp".length()){
        return BladeTokenId.T_BLADE_ENDPHP;
    }
    
    yypushback("@endphp".length());
    return BladeTokenId.T_BLADE_PHP;
            }
          case 86: break;
          case 40: 
            { return BladeTokenId.T_BLADE_ENDPHP;
            }
          case 87: break;
          case 41: 
            { pushState(ST_PHP_LOOKING_FOR_DIRECTIVE_ARG);
    return BladeTokenId.T_BLADE_EXTENDS;
            }
          case 88: break;
          case 42: 
            { pushState(ST_PHP_LOOKING_FOR_DIRECTIVE_ARG);
    return BladeTokenId.T_BLADE_SECTION;
            }
          case 89: break;
          case 43: 
            { pushState(ST_PHP_LOOKING_FOR_DIRECTIVE_ARG);
    return BladeTokenId.T_BLADE_INCLUDE;
            }
          case 90: break;
          case 44: 
            { pushState(ST_PHP_LOOP_EXPR);
    return BladeTokenId.T_BLADE_FOREACH;
            }
          case 91: break;
          case 45: 
            { String ttext = yytext();
    popState();
    return BladeTokenId.T_BLADE_ENDPHP;
            }
          case 92: break;
          case 46: 
            { return BladeTokenId.T_BLADE_ENDSECTION;
            }
          case 93: break;
          case 47: 
            { return BladeTokenId.T_BLADE_ENDFOREACH;
            }
          case 94: break;
      //end of value
      default:
        if (zzInput == YYEOF) {
            if (input.readLength() > 0) {
                // backup eof
                String yytext = yytext();
                input.backup(1);
                //and return the text as error token
                if (zzLexicalState == ST_COMMENT) {
                    return BladeTokenId.T_BLADE_COMMENT;
                } else if (zzLexicalState == ST_BLADE_ECHO || zzLexicalState == ST_BLADE_ECHO_ESCAPED) {
                    return BladeTokenId.T_BLADE_OPEN_ECHO;
                } else if (zzLexicalState == ST_PHP) {
                    return BladeTokenId.T_BLADE_PHP;
                } else if (zzLexicalState == ST_BLADE_PHP) {
                    return BladeTokenId.T_BLADE_PHP;
                } else if (zzLexicalState == ST_DIRECTIVE_ARG) {
                    return BladeTokenId.T_HTML;
                }
                return BladeTokenId.T_HTML;
            } else {
                String yytext = yytext();
                return null;
            }
        } else {
            String yytext = yytext();
            int testState = zzLexicalState;
            zzScanError(ZZ_NO_MATCH);
            //no match
        }
      }
    }
  }


}
