
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Dec 18 08:33:14 EET 2021
//----------------------------------------------------

package org.netbeans.modules.php.blade.editor.parsing;

/** CUP generated interface containing symbol constants. */
public interface ASTBladeSymbols {
  /* terminals */
  public static final int T_REFERENCE = 57;
  public static final int T_SEMICOLON = 52;
  public static final int T_DNUMBER = 27;
  public static final int T_BLADE_INLINE_PHP = 7;
  public static final int T_ARRAY = 32;
  public static final int T_TILDA = 73;
  public static final int T_BLADE_CLOSE_ECHO = 6;
  public static final int T_BLADE_ENDIF = 20;
  public static final int T_BLADE_IF = 18;
  public static final int T_PAAMAYIM_NEKUDOTAYIM = 33;
  public static final int T_BLADE_ENDFOR = 17;
  public static final int T_VAR_COMMENT = 35;
  public static final int T_MINUS_EQUAL = 42;
  public static final int T_BOOLEAN_OR = 53;
  public static final int T_XOR_EQUAL = 49;
  public static final int T_BLADE_ENDFOREACH = 15;
  public static final int T_SPACESHIP = 64;
  public static final int T_STRING = 28;
  public static final int T_INLINE_PHP = 3;
  public static final int T_BLADE_ENDSECTION = 10;
  public static final int T_AT = 77;
  public static final int T_ARRAY_ASSIGN = 88;
  public static final int T_EQUAL = 40;
  public static final int T_CLOSE_RECT = 79;
  public static final int T_SR = 68;
  public static final int T_BLADE_EXTENDS = 12;
  public static final int T_OPEN_RECT = 78;
  public static final int T_NEKUDA = 74;
  public static final int T_BLADE_INCLUDE = 8;
  public static final int T_SL = 67;
  public static final int T_INC = 75;
  public static final int T_KOVA = 56;
  public static final int T_BOOLEAN_AND = 54;
  public static final int T_STRING_VARNAME = 29;
  public static final int T_DIV_EQUAL = 44;
  public static final int T_BLADE_PHP_ECHO = 23;
  public static final int T_AND_EQUAL = 47;
  public static final int T_VARIABLE = 30;
  public static final int T_SR_EQUAL = 51;
  public static final int T_SL_EQUAL = 50;
  public static final int T_BLADE_COMMENT = 4;
  public static final int T_ENDIF = 81;
  public static final int T_ELSEIF = 82;
  public static final int T_MINUS = 70;
  public static final int T_IS_EQUAL = 58;
  public static final int T_OR_EQUAL = 48;
  public static final int T_INLINE_HTML = 2;
  public static final int T_NEW = 80;
  public static final int T_MOD_EQUAL = 46;
  public static final int T_DOLLAR = 87;
  public static final int T_NEKUDOTAIM = 86;
  public static final int EOF = 0;
  public static final int T_PLUS = 69;
  public static final int T_NUM_STRING = 31;
  public static final int T_IS_SMALLER_OR_EQUAL = 62;
  public static final int T_LNUMBER = 26;
  public static final int T_BLADE_YIELD = 13;
  public static final int T_IS_NOT_EQUAL = 59;
  public static final int T_PRECENT = 71;
  public static final int T_NUMBER = 25;
  public static final int T_PLUS_EQUAL = 41;
  public static final int error = 1;
  public static final int T_PHP_CONDITION_EXPRESSION = 24;
  public static final int T_ELSE = 83;
  public static final int T_RGREATER = 65;
  public static final int T_BLADE_FOREACH = 14;
  public static final int T_IS_IDENTICAL = 60;
  public static final int T_BLADE_SHOW = 11;
  public static final int T_PHP_LOOP_EXPRESSION = 22;
  public static final int T_NS_C = 34;
  public static final int T_IS_NOT_IDENTICAL = 61;
  public static final int T_BLADE_OPEN_ECHO = 5;
  public static final int T_LOGICAL_AND = 39;
  public static final int T_IS_GREATER_OR_EQUAL = 63;
  public static final int T_BLADE_SECTION = 9;
  public static final int T_BLADE_FOR = 16;
  public static final int T_LOGICAL_OR = 37;
  public static final int T_CLOSE_PARENTHESE = 85;
  public static final int T_NOT = 72;
  public static final int T_LOGICAL_XOR = 38;
  public static final int T_CONCAT_EQUAL = 45;
  public static final int T_OPEN_PARENTHESE = 84;
  public static final int T_OR = 55;
  public static final int T_COMMA = 36;
  public static final int T_DEC = 76;
  public static final int T_MUL_EQUAL = 43;
  public static final int T_BLADE_ELSEIF = 19;
  public static final int T_LGREATER = 66;
  public static final int T_BLADE_DIRECTIVE = 21;
}

